### ISSUE TITLE
The ExampleNewClient test is failing on 1.9 and 1.10 intermittently

### ISSUE THREAD

**Issue by rbriski** [andygrunwald/go-jira#161]
Travis runs on recent PRs are throwing errors on `ExampleNewClient`

**Comment by andygrunwald** [comment]
It seems to be something related to network or to the external JIRA instance, because if you repeat the tests, sometimes they succeed. So they are flaky somehow.

See the builds here:
- https://travis-ci.org/andygrunwald/go-jira/builds/426393620
- https://travis-ci.org/andygrunwald/go-jira/builds/426151774
- https://travis-ci.org/andygrunwald/go-jira/builds/425847237
