### ISSUE TITLE
Welcome Wes (aka ghostsquad) - a new maintainer 

### ISSUE THREAD

**Issue by andygrunwald** [andygrunwald/go-jira#201]
I would like to Welcome @ghostsquad 

Since yesterday, he is an additional contributor/collaborator with merge rights. I added him to the team. Recently he was quite active in the project, also by helping others out with comments and issues.

Welcome! 🍻 ☕️

**Comment by ghostsquad** [comment]
👋

**Comment by ghostsquad** [comment]
@andygrunwald I think we should look for another maintainer of this, and possibly move the repo to an organization. I haven't been doing much in Jira in the last 6 months or so, and as a result, I don't have a lot of incentive to fix any ongoing issues, or move forward with the v2 rework in order to support some backwards incompatible changes.

I've been at least responding to issues, and approving PRs though. So that's something. Let me know what you want to do.

**Comment by andygrunwald** [comment]
Sounds reasonable, @ghostsquad.
Thanks a lot for your efforts.

As you might have seen, this is nearly the same situation where I am in.
Do you have any idea/recommendation on how or where to look for a new maintainer?
Or maybe even two? The number of issues and PRs are not getting less.

I am open to every suggestion:
- Shout out via twitter?
- Asking if we can get a spot at https://golangweekly.com/ ?

Maybe the first action is open an issue, pin it and link it in the README.
Let me take this over. I try to come up with something.

Any requirements you would love to see in new maintainers?

The organization-part sounds also reasonable. Maybe this can be a move once we found new people.

**Comment by ghostsquad** [comment]
All of the above!

Regarding requirements, I think generally speaking, the contribution guidelines should be updated and strictly enforced. I made a PR template which I think should also be enforced. I think a maintainer who knows how to keep changes backwards compatible, and knows how to test, BDD, Unit, Acceptance, that sort of thing would be most useful.

I don't necessarily plan on leaving, so I'm happy to help review PRs, do releases, and other such tasks as needed. If someone more junior shows interest, I think that's cool. ☺️

Are you interested in helping me do PR reviews as needed?

**Comment by andygrunwald** [comment]
> the contribution guidelines should be updated and strictly enforced
Can we (maybe) leverage GitHub actions to automate parts of it?

> Are you interested in helping me do PR reviews as needed?
Sure. Maybe we can also get a call together and talk about how we organize it, what we can do to make it easier to contribute or make this API more stable and how to deal/move forward with breaking changes that make sense (e.g.. lifecycle of future versions).

Another idea might also to get in contact with Atlassian to get a JIRA instance where we can run integration-tests.

What do you think? Interested?
If yes, which timezone are you living in? I am living in Germany (UTC + 2)

Re new contributors:
I would love to get new + motivated people on board. However, this is a part where nearly every open source project is struggling with. Maybe until we found new people, we can share the workload, I get more active again and we have a clear roadmap/plan?

**Comment by ghostsquad** [comment]
I wonder if maybe Atlassian would be interested in officially supporting or sponsoring this framework.

I'm US West (UTC - 7)

GitHub actions sounds good.

I'm not going to say no to you getting more active. :wink: The library is already pretty stable as is, and it's getting use, which I think is great, which is why people are contributing PRs for new features and bug fixes.

I think we could also get some support by opening the repo to GitHub sponsorships and using OpenCollective to help with some of the financial incentives.

**Comment by andygrunwald** [comment]
I think we are done here so far.
