### ISSUE TITLE
Product naming consistency: JIRA vs. Jira

### ISSUE THREAD

**Issue by andygrunwald** [andygrunwald/go-jira#284]
The product is named `Jira`.

In our library, we write Jira in multiple ways. Sometimes JIRA, sometimes Jira.
Should we unify and make it more consistent and align this with the official project?

This would indicate naming the product everywhere `Jira`.

What do you think?

**Comment by ghostsquad** [comment]
I did a quick search, and Atlassian seems to consistently use `Jira`, though others I see use `JIRA`. I think we should stick with following the creators/owners.

**Comment by ghostsquad** [comment]
Since PR #286 has already been merged, this probably should have been closed already.

@andygrunwald check out this page for the proper way to close issues:

https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

You commit was _very_ close. Instead of

```
closes issue #284
```

it should have been

```
closes #284
```
