### ISSUE TITLE
Which Jira product are we supporting?

### ISSUE THREAD

**Issue by andygrunwald** [andygrunwald/go-jira#295]
## Is your feature request related to a problem?

Jira is available in two different product versions:

- [Jira cloud](https://developer.atlassian.com/cloud/jira/platform/)
- [Jira server](https://developer.atlassian.com/server/jira/platform/rest-apis/)

This project was initially started + used with an on-premise Jira installation (Jira server).
Over time more and more Jira cloud API endpoints landed in this library. See https://github.com/andygrunwald/go-jira/blob/e1f4265e2b467b938fe0c095caf6d36f3136d2ff/user.go#L12

Right now we have the case that we mix the endpoints in this library.
Personally, I don't know 
- If the APIs of Jira cloud and Jira server are different / how much they overlap
- how much of the cloud/server endpoints work in the different product version

However, reality is: I am not aware of any issue about the overlapping problem described.

## Describe the solution you'd like

The big question to answer:

Which product are we officially supporting/aim to support?
- One? Which one?
- Both? If yes, how? Explicit split? A wild mix like we have now?

Additional question for the cloud product:
- API version 2?
- or/and API version 3? (still in beta)

## Additional context

- [Jira Server Developer: REST APIs](https://developer.atlassian.com/server/jira/platform/rest-apis/)
- [Jira Server platform REST API reference (Jira v8.8.1)](https://docs.atlassian.com/software/jira/docs/api/REST/8.8.1/)
- [Jira Cloud platform Developer: REST API v2](https://developer.atlassian.com/cloud/jira/platform/rest/v2/)
- [Jira Cloud platform Developer: REST API v3 (beta)](https://developer.atlassian.com/cloud/jira/platform/rest/v3/)

**Comment by andygrunwald** [comment]
@rbriski @ghostsquad @suhaibmujahid Any opinions here?

**Comment by ghostsquad** [comment]
I think we should support them all, but like other projects, stop supporting old versions. Though in general, this is a bit hard to do properly, since we would likely need a variety of API versions to test against, both cloud and server. @andygrunwald have you reached out to Atlassian about this? Maybe they would sponsor this project and provide us with testing endpoints.

**Comment by suhaibmujahid** [comment]
In my case, my application interacts with both of the Jira Server and Jira Cloud. To my knowledge, both have almost the same API ([see here](https://community.atlassian.com/t5/Jira-questions/Difference-between-Jira-Cloud-REST-API-and-Server-REST-API/qaq-p/658434)). They differ mainly in the authentication, which is out of the scope of this package.

Form a usability point of view, a wild mix could be a better option. In this way, the user can interact with both Jira Could and Jira Server without the need to have an extra wrapper layer.

I think it is better to support API version 2 (at least for now) since it is kind of compatible with both Jira Could and Jira Server. If we face inconsistency (if any) we could handle it one by one and document it if needed.

I think it is the user's responsibility to know the expected behavior of Jira itself. On the client-side, it is good if we manage to correctly handle the API calls and having a general enough structs to include all the exposed fields/options.

**Comment by mansilladev** [comment]
If you're truly looking to support both cloud and server, I suggest making the separation/choice explicit. They're diverging in more ways than just auth. For example, Jira expressions (https://developer.atlassian.com/cloud/jira/platform/jira-expressions/) on the cloud side.. amongst other nuances that could get conflated and confusing as they may continue to diverge.

**Comment by ghostsquad** [comment]
I agree. This may come at the cost of duplicating some code. Even their documentation is split depending on cloud vs server.

https://developer.atlassian.com/server/jira/platform/rest-apis/

https://developer.atlassian.com/cloud/jira/platform/rest/v3/

In v2 we probably should have cloud/server packages, that potentially call to common code elsewhere, just so that we can support both, but also allow us to make explicit decisions for cloud vs server endpoints/calls.

**Comment by ghostsquad** [comment]
I'm concerned at our ability to test either though. We don't have a public server that we can run end2end tests against

**Comment by andygrunwald** [comment]
@ghostsquad 
I have reached out to Atlassian about getting an instance sponsored. Seems that this is not possible at the moment. @mansilladev Can you confirm this? Do you see an opportunity to help us here?
This would make the development + testing easier.

**Comment by rishu2403** [comment]
Hello @andygrunwald , I am not able to setup auth and use get user fucntion. Do we have seperate sever package ?

**Comment by andygrunwald** [comment]
Fixed in https://github.com/andygrunwald/go-jira/pull/492/
