### ISSUE TITLE
Support Context for HTTP requests

### ISSUE THREAD

**Issue by fallais** [andygrunwald/go-jira#337]
Would it be possible to add Context support for HTTP requests please ?

**Comment by andygrunwald** [comment]
Hey @fallais,
yeah, sure. Thanks for this issue. integrating and adding support for the context package is something we would love to have.
Right now, we have a few methods with a suffix `WithContext` that support it already.
However, it is not widely implemented yet, but we are happy to receive PRs on this.

As a side note: We are collecting ideas for v2 to fix several topics in this package, see https://github.com/andygrunwald/go-jira/issues/200

**Comment by andygrunwald** [comment]
Hey,

I am very sorry that this issue has been open for a long time with no final solution. We work on this project in our spare time, and sometimes, other priorities take over. This is the typical open source dilemma.

#### However, there is news: **We are kicking off v2 of this library 🚀** 

To provide visibility, we created the [Road to v2](https://github.com/andygrunwald/go-jira/milestone/1) Milestone and calling for your feedback in https://github.com/andygrunwald/go-jira/issues/489

The development will take some time; however, I hope you can benefit from the changes.
If you seek priority development for your issue + you like to sponsor it, please contact me.

#### What does this mean for my issue?

We will work on this issue indirectly.
This means that during the development phase, we aim to tackle it.
Maybe in a different way like it is currently handled.
Please understand that this will take a while because we are running this in our spare time.

#### Final words

Thanks for using this library.
If there is anything else you would like to tell us, let us know!

**Comment by andygrunwald** [comment]
Previous work: https://github.com/andygrunwald/go-jira/pull/363

**Comment by andygrunwald** [comment]
Previous work: https://github.com/andygrunwald/go-jira/commit/e1f4265e2b467b938fe0c095caf6d36f3136d2ff

**Comment by andygrunwald** [comment]
Fixed in #513, #514, #515
