### ISSUE TITLE
Unable to make issue transition with payload

### ISSUE THREAD

**Issue by CondensedTea** [andygrunwald/go-jira#436]
## Is your feature request related to a problem? Please describe.

Jira API supports performing issue transition with comments in `update` field, but go-jira doesnt provide this functionality.

## Describe the solution you'd like

It would be nice if CreateTransitionPayload struct had update field per Jira API [documentation](https://docs.atlassian.com/software/jira/docs/api/REST/6.2.7/#d2e1312)

I've updated CreateTransitionPayload  in #423 

## Describe alternatives you've considered

Users of go-jira can write their own custom versions of CreateTransitionPayload and use it alongside with go-jira

**Comment by andygrunwald** [comment]
Hey,

I am very sorry that this issue has been open for a long time with no final solution. We work on this project in our spare time, and sometimes, other priorities take over. This is the typical open source dilemma.

#### However, there is news: **We are kicking off v2 of this library 🚀** 

To provide visibility, we created the [Road to v2](https://github.com/andygrunwald/go-jira/milestone/1) Milestone and calling for your feedback in https://github.com/andygrunwald/go-jira/issues/489

The development will take some time; however, I hope you can benefit from the changes.
If you seek priority development for your issue + you like to sponsor it, please contact me.

#### What does this mean for my issue?

We will work on this issue indirectly.
This means that during the development phase, we aim to tackle it.
Maybe in a different way like it is currently handled.
Please understand that this will take a while because we are running this in our spare time.

#### Final words

Thanks for using this library.
If there is anything else you would like to tell us, let us know!
