### ISSUE TITLE
Getting an Issue's linked epic returns nil pointer

### ISSUE THREAD

**Issue by lukehumphreys** [andygrunwald/go-jira#50]
When trying to get a linked Epic for a Story a nil pointer is returned even when the story has a linked epic.

``` go
func main() {
	jiraClient, _ := jira.NewClient(nil, "https://issues.apache.org/jira/")
	issue, _, _ := jiraClient.Issue.Get("MESOS-3078")

	fmt.Printf(issue.Fields.Epic.Name)
}
```

This returns:
`panic: runtime error: invalid memory address or nil pointer dereference`

Even though there is an epic link:
[MESOS-3078](https://issues.apache.org/jira/browse/MESOS-3078)

**Comment by andygrunwald** [comment]
Hey @lukehumphreys,

when you fire a simply `jiraClient.Issue.Get("MESOS-3078")`, an epic is represented as a custom field. The epic field is not a native field by Jira. It will be added by the [Greenhopper agile plugin](https://de.atlassian.com/software/jira/agile).
In this JIRA instance it will be represented as `customfield_12311120`:

```go
package main

import (
	"github.com/andygrunwald/go-jira"
	"fmt"
)

func main() {
	jiraClient, _ := jira.NewClient(nil, "https://issues.apache.org/jira/")
	issue, _, _ := jiraClient.Issue.Get("MESOS-3078")

	fmt.Printf("%+v", issue.Fields.Unknowns["customfield_12311120"])
}
```

leads to the result

```
$ go run jira.go
MESOS-4766%
```

This is described here as well: https://docs.atlassian.com/jira-software/REST/cloud/#agile

> The Epic link custom field contains the key of an epic that a given issue belongs to. Be aware that only the issue key of the existing epic can be set. Also, the epic link cannot be set for sub-tasks and epics.

The Epic struct was added in #28.
The reason why this was added comes from #26.
But i guess this is a different perspective, because #26 is getting all issues in a sprint. But you want to access the epic based on an issue.

**Comment by andygrunwald** [comment]
No answer since ~2 month. Closing now.
