### ISSUE TITLE
support for oauth2 used by Jira Add-Ons

### ISSUE THREAD

**Issue by shdunning** [andygrunwald/go-jira#93]
In order to support REST API calls from Jira Add-Ons created through the Atlassian Connect framework, we need to: 

1. create a JSON Web Token (JWT) assertion
2. use the JWT assertion + secret to get an access token
3. include the access token in the request headers

I've got a working standalone example and I'll create a PR in a bit.

**Comment by rbriski** [comment]
`oauth2` support is pretty limited to the HTTP client, correct?  If so, wouldn't it be best to keep it separate from the `go-jira` code but still link to it in the README like the current `oauth1` docs?

https://gist.github.com/Lupus/edafe9a7c5c6b13407293d795442fe67

**Comment by shdunning** [comment]
It is, except there is some of non-trivial Jira / Atlassian specific stuff in there -- like creating [JSON Web Tokens](https://developer.atlassian.com/cloud/jira/software/understanding-jwt/). I was hoping the PR I'm about to put together will save people some time in the future.

**Comment by shdunning** [comment]
@rbriski take a look at #95 and see what you think.

**Comment by andygrunwald** [comment]
Hey @shdunning and @rbriski, thanks for your effort.
Since some days i think about to renew go-jira and make it more structured.
In this move i thought about keep auth in generale outside of this lib. Like the go-github library here: https://github.com/google/go-github#authentication

I didnt have a deeper look at the JWT topic (yet). Do you think we can do it somehow with a http.RoundTripper?

I will try to check this in the next days, but i can't promise anything (some priorities in my real life)

**Comment by shdunning** [comment]
@andygrunwald sorry it took so long to respond. I don't know much about http.RoundTripper, but I wouldn't be surprised if you couldn't do it all in the `http.Client*` reference and then pass that into go-jira. In my PR, however, I was trying to make it easier for folks that might want to use go-jira to help build a Jira Add-On via the Atlasssian Connect framework. WRT JWT, there is some Jira-specific stuff that my PR abstracts so future users don't have to fumble their way through the Oauth2 dance with the Jira auth servers.

Let me know what you decide as we have my fork running in production to support a Jira Add-On integration with our system. If we decide to not include my PR, then I'd have to revisit this approach and figure out how to do the JWT stuff outside of go-jira.

Thanks!

**Comment by andygrunwald** [comment]
Thanks for the update. Right now i am quite limited in time to review and test this (private priorities).
So please dont delete your fork here. Once i have time again i will start reviewing it, ok?

In general: I am open for this / such a feature set. I am not 100% sure what the best solution is or now. I know to less about the JWT topic.

I will come back once i have a little bit more spare time, fine?

**Comment by rbriski** [comment]
I've been messing around with this a little.  It looks like `RoundTripper` is the idiomatic way to add middleware into http clients.  Here's an example of authentication being added into the client:
https://github.com/vadimi/go-http-ntlm

I'm going to keep looking at this.  I think the best way to handle it would be to create an interface so that anyone that implements the interface can drop their `RoundTripper` into the transport for the http client.  More later, as I have time.

**Comment by andygrunwald** [comment]
I really like how go-github is doing this.
See docs here: https://github.com/google/go-github#authentication

Here is an implementation for BasicAuth via RoundTripper: https://github.com/google/go-github/blob/master/github/github.go#L895

I think this is a nice way, because it is not 100% build into the lib.

**Comment by rbriski** [comment]
Yes, I think the better example of what the syntax should look like is right about the basic auth code:
```go
t := &github.UnauthenticatedRateLimitedTransport{
  ClientID:     "your app's client ID",
  ClientSecret: "your app's client secret",
  }
client := github.NewClient(t.Client())
```

**Comment by rbriski** [comment]
I closed #95 and I'm moving the rest of the conversation to here.

**Comment by shdunning** [comment]
@rbriski these are looking good from a completeness standpoint:
https://github.com/rbriski/atlassian-jwt
https://github.com/rbriski/atlassian-jwt/blob/master/examples/jwt/main.go

The use case I was trying to solve with my PR was just server <-> server communication over Ouath2 (meaning, add-on is already installed, install/uninstall + webhook handlers are registered, shared secret is stored, etc...). Let's make sure we can still easily support this use case too; that is: "I know the `sharedSecret`,  I just need to request an Oauth2 token."

Looking good so far!

**Comment by rbriski** [comment]
@shdunning , simple JWT bearer-token authentication will work for install/uninstall/webhook work as long as you're reading or writing as the user that installed the add-on (admin in many cases).

The only time you need oauth2 is for ACTS_AS_USER capabilities when you actually want to act as a user other than the one that installed the add-on.  The install security context returns different info if you include that scope in your atlassian-connect JSON doc.

I'm going to try to add handling for JIRA oauth2 to the https://github.com/golang/oauth2 library if it will work.  If JIRA is too different, I'll just add it to the jwt library I linked to above.

**Comment by rbriski** [comment]
@shdunning I'm trying to add oauth2 to my library but I can't get JIRA to return the oauthClientID.  I see that field in the code you submitted but I don't see how you get it.  Where did you get the oauthClientID?

**Comment by rbriski** [comment]
Nevermind, I figured out the issue.

**Comment by rbriski** [comment]
@shdunning My change was accepted into the Go stdlib (https://go-review.googlesource.com/c/oauth2/+/102037).  You can now use JIRA through `golang.org/x/oauth2/jira`.  I'll add an example in my auth repo and include it here before closing this ticket.

**Comment by shdunning** [comment]
@andygrunwald @rbriski i got this working in our env following this example: https://github.com/rbriski/atlassian-jwt/pull/2/files

I think we can close this issue out now.

Thanks to you both for all the help!
